apiVersion: apps/v1
kind: deployment
metadata:
  name: student-app
  label:
    app: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: ghcr.io/James-Zhang-Devops/student-core-infra:latest
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "latest"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProde:
          httpGet:
            path: /health
            port: 8080
          inittialDelaySeconds: 30
          periodSeconds: 10
        readinessProde:
          httpGet:
            path: /health
            port: 8080
          initailDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: services
metadata:
  name: student-app-services
spec:
  selector:
    app: student-app
    ports:
    - port: 80
      targetPort: 8080
    type: LoadBalancer 